import { AIModel, ModelComparison } from '@/types/ai-models';

export const AI_MODELS: AIModel[] = [
  {
    id: 'claude-4-opus',
    slug: 'claude-4-opus',
    name: 'Claude 4 Opus',
    nameEn: 'Claude 4 Opus',
    company: 'Anthropic',
    companyEn: 'Anthropic',
    logo: '🟠',
    category: 'text',
    pricing: 'paid',
    pricingDetails: 'مدفوع — يتوفر عبر API وClaude Pro ($20/شهر)',
    website: 'https://claude.ai',
    description: 'أحدث وأقوى نموذج من Anthropic. يتميز بالتفكير العميق والتحليل المنطقي المتقدم وكتابة النصوص الطويلة بدقة عالية. ممتاز للمهام المعقدة التي تتطلب تفكيراً عميقاً.',
    descriptionEn: 'The latest and most powerful model from Anthropic. Excels at deep thinking, complex logical analysis, and long-form writing with high accuracy.',
    strengths: ['تفكير عميق ومنطقي ممتاز', 'سياق أقصى يصل لـ 200K توكن', 'كتابة نصوص طويلة ومتقنة', 'فهم عميق للمهام المعقدة', 'ared من الإجابات الكاذبة'],
    weaknesses: ['أبطأ من GPT-4o في الاستجابات السريعة', 'لا يدعم توليد الصور', 'مدفوع بالكامل'],
    bestFor: ['التحليل المنطقي المعقد', 'كتابة المقالات والأخبار الطويلة', 'مراجعة الكود وتصحيح الأخطاء', 'البحث الأكاديمي', 'المهام التي تتطلب دقة عالية'],
    contextWindow: '200,000 توكن',
    languages: ['العربية', 'الإنجليزية', 'الفرنسية', 'الألمانية', 'الإسبانية', '+30 لغة'],
    releasedDate: '2025',
    version: '4.0',
    features: [
      { name: 'Extended Thinking', nameAr: 'التفكير الممتد', description: 'يؤدي تفكيراً عميقاً قبل الإجابة — ممتاز للمهام المعقدة' },
      { name: 'Artifacts', nameAr: 'النواتج', description: 'يولد كوداً تفاعلياً ومخططات ومستندات مباشرة' },
      { name: 'Projects', nameAr: 'المشاريع', description: 'تنظيم المحادثات في مشاريع مع سياق مستمر' },
      { name: 'Computer Use', nameAr: 'استخدام الحاسوب', description: 'يمكنه التفاعل مع واجهات الحاسوب والتطبيقات' },
    ],
    tips: [
      'استخدم "Think step by step" للحصول على تحليل أعمق',
      'أضف السياق الكامل في أول رسالة لتقليل الأخطاء',
      'استخدم Projects لتنظيم محادثات العمل المستمرة',
      'عند المقارنة مع GPT-4o، Claude أفضل في النصوص الطويلة'
    ]
  },
  {
    id: 'claude-3-5-sonnet',
    slug: 'claude-3-5-sonnet',
    name: 'Claude 3.5 Sonnet',
    nameEn: 'Claude 3.5 Sonnet',
    company: 'Anthropic',
    companyEn: 'Anthropic',
    logo: '🟠',
    category: 'text',
    pricing: 'freemium',
    pricingDetails: 'مجاني محدود + مدفوع عبر API',
    website: 'https://claude.ai',
    description: 'نموذج متوازن من Anthropic — أسرع من Opus وأقل تكلفة مع أداء ممتاز في معظم المهام. الخيار الأمثل للاستخدام اليومي.',
    descriptionEn: 'A balanced model from Anthropic — faster than Opus and more affordable with excellent performance for most tasks.',
    strengths: ['سرعة جيدة مع أداء عالي', 'ممتاز في البرمجة', 'فهم عميق للسياق الطويل', 'مجاني للاستخدام الأساسي'],
    weaknesses: ['لا يدعم توليد الصور', 'أقل دقة من Opus في المهام المنطقية جداً', 'سياق أقل من Opus'],
    bestFor: ['البرمجة وتطوير البرمجيات', 'الكتابة اليومية', 'التحليل السريع', 'الردود التفاعلية'],
    contextWindow: '200,000 توكن',
    languages: ['العربية', 'الإنجليزية', '+20 لغة'],
    releasedDate: '2024',
    version: '3.5',
    features: [
      { name: 'Fast Response', nameAr: 'استجابة سريعة', description: 'أسرع استجابة من Opus مع الحفاظ على الجودة' },
      { name: 'Code Excellence', nameAr: 'تميز البرمجة', description: 'ممتاز في كتابة وفهم وتصحيح الكود' },
    ],
    tips: [
      'استخدمه للمهام اليومية السريعة بدلاً من Opus',
      'ممتاز لتدقيق الكود واقتراح التحسينات',
      'أضف "respond in Arabic" للحصول على ردود عربية مباشرة'
    ]
  },
  {
    id: 'gpt-4o',
    slug: 'gpt-4o',
    name: 'GPT-4o',
    nameEn: 'GPT-4o',
    company: 'OpenAI',
    companyEn: 'OpenAI',
    logo: '🟢',
    category: 'multimodal',
    pricing: 'freemium',
    pricingDetails: 'مجاني محدود + ChatGPT Plus ($20/شهر) + API',
    website: 'https://chat.openai.com',
    description: 'النموذج الرئيسي من OpenAI — متعدد الوسائط يفهم النصوص والصور والصوت. الأسرع في الاستجابة ويدعم الميزات التفاعلية الأكثر.',
    descriptionEn: 'The flagship model from OpenAI — multimodal, understands text, images, and audio. Fastest response time with the most interactive features.',
    strengths: ['متعدد الوسائط (نص + صورة + صوت)', 'سرعة استجابة ممتازة', 'يدعم DALL-E لتوليد الصور', 'ذاكرة طويلة المدى', 'يدعم البحث عن الإنترنت'],
    weaknesses: ['أحياناً يختلق معلومات', 'السياق الأقصى أقل من Claude', 'ราคาAPI مرتفع نسبياً'],
    bestFor: ['المحادثات التفاعلية السريعة', 'توليد الصور بالنصوص', 'البحث عن الإنترنت', 'التحليل البصري للصور', 'المهام المتعددة الوسائط'],
    contextWindow: '128,000 توكن',
    languages: ['العربية', 'الإنجليزية', '+50 لغة'],
    releasedDate: '2024',
    version: '4o',
    features: [
      { name: 'DALL-E Integration', nameAr: 'تكامل DALL-E', description: 'توليد صور مباشرة من النص في المحادثة' },
      { name: 'Web Browsing', nameAr: 'البحث عن الإنترنت', description: 'يمكنه البحث والتحقق من المعلومات المحدثة' },
      { name: 'Memory', nameAr: 'الذاكرة', description: 'يتذكر محادثاتك السابقة ويتعلم من تفضيلاتك' },
      { name: 'Code Interpreter', nameAr: 'مفسر الكود', description: 'يكتب ويexe كود Python مباشرة' },
      { name: 'Custom GPTs', nameAr: 'GPTs مخصصة', description: 'إنشاء نماذج مخصصة لمهام معينة' },
    ],
    tips: [
      'استخدم "browse the web" للحصول على معلومات محدثة',
      'ارفق صورة واطلب تحليلها — GPT-4o الأفضل في الفهم البصري',
      'استخدم Custom GPTs لإنشاء مساعدات متخصصة',
      'فعّل الذاكرة لتذكر تفضيلاتك عبر المحادثات'
    ]
  },
  {
    id: 'gpt-o3',
    slug: 'gpt-o3',
    name: 'GPT-o3',
    nameEn: 'GPT-o3',
    company: 'OpenAI',
    companyEn: 'OpenAI',
    logo: '🟢',
    category: 'text',
    pricing: 'paid',
    pricingDetails: 'مدفوع — متاح في ChatGPT Pro ($200/شهر) + API',
    website: 'https://openai.com',
    description: 'نموذج التفكير المتقدم من OpenAI — مصمم للمهام المنطقية والرياضية والعلمية الأكثر تعقيداً. يفكر بعمق قبل الإجابة.',
    descriptionEn: 'The advanced reasoning model from OpenAI — designed for the most complex logical, mathematical, and scientific tasks.',
    strengths: ['تفكير منطقي متقدم جداً', 'ممتاز في الرياضيات والفيزياء', 'يحل مسائل معقدة خطوة بخطوة', 'أدق نموذج من OpenAI في التحليل'],
    weaknesses: ['أبطأ من GPT-4o بشكل ملحوظ', 'أغلى تكلفة', 'لا يدعم الصور أو الصوت', 'محدود الإطلاق'],
    bestFor: ['المسائل الرياضية والعلمية المعقدة', 'التحليل المنطقي العميق', 'الأبحاث العلمية', 'البرمجة المتقدمة', 'مسائل التخمين المنطقي'],
    contextWindow: '200,000 توكن',
    languages: ['الإنجليزية', 'العربية', '+10 لغات'],
    releasedDate: '2025',
    version: 'o3',
    features: [
      { name: 'Deep Reasoning', nameAr: 'التفكير العميق', description: 'يحلل المسائل خطوة بخطوة قبل تقديم الإجابة' },
      { name: 'Chain of Thought', nameAr: 'سلسلة التفكير', description: 'يعرض عملية تفكيره الكاملة' },
    ],
    tips: [
      'استخدمه فقط للمهام التي تحتاج تفكيراً عميقاً — لا تستخدمه للمحادثات العادية',
      'اطلب "show your reasoning" لرؤية خطوات التفكير',
      'ممتاز لمسائل الرياضيات والفيزياء والكيمياء'
    ]
  },
  {
    id: 'gemini-2-5-pro',
    slug: 'gemini-2-5-pro',
    name: 'Gemini 2.5 Pro',
    nameEn: 'Gemini 2.5 Pro',
    company: 'Google',
    companyEn: 'Google',
    logo: '🔵',
    category: 'multimodal',
    pricing: 'freemium',
    pricingDetails: 'مجاني عبر Gemini + API مدفوع',
    website: 'https://gemini.google.com',
    description: 'أحدث نموذج من Google — سياق ضخم يصل لـ 1 مليون توكن + فهم بصري ممتاز + تكامل مع خدمات Google. الأفضل في معالجة المعلومات الكبيرة.',
    descriptionEn: 'Latest model from Google — massive 1M token context + excellent visual understanding + Google services integration. Best for processing large information.',
    strengths: ['سياق أقصى 1,000,000 توكن (الأكبر)', 'فهم ممتاز للصور والفيديو', 'تكامل مع Google Workspace', 'مجاني للاستخدام الأساسي', 'سرعة جيدة'],
    weaknesses: ['أحياناً يفتقر للعمق في التحليل', 'لا يزال أقل ثقة من Claude في المهام المنطقية', 'الخصوصية — بياناتك تستخدم لتدريب Google'],
    bestFor: ['تحليل مستندات طويلة جداً', 'فهم الصور والفيديوهات', 'التكامل مع Gmail وGoogle Docs', 'البحث العميق في نصوص كبيرة', 'الترجمة'],
    contextWindow: '1,000,000 توكن',
    languages: ['العربية', 'الإنجليزية', '+100 لغة'],
    releasedDate: '2025',
    version: '2.5',
    features: [
      { name: 'Million Token Context', nameAr: 'سياق مليون توكن', description: 'يمكنك تحليل كتب كاملة أو ملفات ضخمة دفعة واحدة' },
      { name: 'Google Workspace', nameAr: 'تكامل Google', description: 'يتصل بـ Gmail وGoogle Docs وGoogle Drive مباشرة' },
      { name: 'Code Execution', nameAr: 'تنفيذ الكود', description: 'يكتب ويexe كود Python وJavaScript مباشرة' },
      { name: 'Image Understanding', nameAr: 'الفهم البصري', description: 'يحلل الصور والرسوم البيانية والجدول بدقة' },
    ],
    tips: [
      'استخدمه لتحليل مستندات طويلة — أرسل ملف PDF كامل واطلب ملخصه',
      'ارفق صورة رسم بياني واطلب تحليل البيانات',
      'استخدمه مع Google Docs مباشرة للكتابة التعاونية',
      'فعّل Gem لإنشاء مساعدات مخصصة لمهام معينة'
    ]
  },
  {
    id: 'gemini-2-0-flash',
    slug: 'gemini-2-0-flash',
    name: 'Gemini 2.0 Flash',
    nameEn: 'Gemini 2.0 Flash',
    company: 'Google',
    companyEn: 'Google',
    logo: '🔵',
    category: 'text',
    pricing: 'free',
    pricingDetails: 'مجاني بالكامل',
    website: 'https://gemini.google.com',
    description: 'النموذج السريع من Google — مجاني بالكامل وأسرع استجابة. ممتاز للمهام اليومية البسيطة والسريعة.',
    descriptionEn: 'The fast model from Google — completely free with the fastest response time. Great for simple daily tasks.',
    strengths: ['مجاني بالكامل', 'سرعة استجابة ممتازة', 'يدعم الصور والنصوص', 'متوفر على جميع الأجهزة'],
    weaknesses: ['أقل دقة في المهام المعقدة', 'سياق أقل من Pro', 'لا يدعم التفكير الممتد'],
    bestFor: ['المحادثات اليومية السريعة', 'الأسئلة البسيطة', 'الترجمة السريعة', 'تلخيص النصوص القصيرة'],
    contextWindow: '1,000,000 توكن',
    languages: ['العربية', 'الإنجليزية', '+100 لغة'],
    releasedDate: '2024',
    version: '2.0',
    features: [
      { name: 'Free Forever', nameAr: 'مجاني للأبد', description: 'لا يوجد حدود استخدام أو اشتراك' },
      { name: 'Ultra Fast', nameAr: 'فائق السرعة', description: 'أسرع استجابة بين جميع النماذج' },
    ],
    tips: [
      'المثالي للمهام اليومية البسيطة不需要 thought model',
      'استخدم Gemini 2.5 Pro للمهام المعقدة بدلاً منه',
      'ممتاز للترجمة السريعة والأسئلة البسيطة'
    ]
  },
  {
    id: 'gpt-4o-mini',
    slug: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    nameEn: 'GPT-4o Mini',
    company: 'OpenAI',
    companyEn: 'OpenAI',
    logo: '🟢',
    category: 'text',
    pricing: 'free',
    pricingDetails: 'مجاني في ChatGPT + API رخيصة جداً',
    website: 'https://chat.openai.com',
    description: 'النموذج الصغير والسريع من OpenAI — مجاني بالكامل في ChatGPT وأرخص خيار API. ممتاز للمهام البسيطة وال протوتيип السريع.',
    descriptionEn: 'The small and fast model from OpenAI — completely free in ChatGPT and cheapest API option. Great for simple tasks and rapid prototyping.',
    strengths: ['مجاني بالكامل في ChatGPT', 'سرعة استجابة ممتازة', 'API رخيصة جداً ($0.15/1M توكن)', 'ممتاز للمهام البسيطة'],
    weaknesses: ['أقل ذكاءً من GPT-4o', 'لا يدعم تحليل الصور بدقة', 'يصعب في المهام المعقدة'],
    bestFor: ['المحادثات اليومية', 'الأسئلة البسيطة', 'البروتيب السريع', 'الategorization والتصنيف'],
    contextWindow: '128,000 توكن',
    languages: ['العربية', 'الإنجليزية', '+50 لغة'],
    releasedDate: '2024',
    version: '4o-mini',
    features: [
      { name: 'Cheapest API', nameAr: 'أرخص API', description: '$0.15 لكل مليون توكن — مناسب للتطبيقات الكبيرة' },
      { name: 'Free ChatGPT', nameAr: 'مجاني في ChatGPT', description: 'استخدمه مجاناً بدون اشتراك' },
    ],
    tips: [
      'استخدمه في تطبيقاتك إذا كنت تريد تقليل تكلفة API',
      'ممتاز لتصنيف النصوص ومعالجة البيانات البسيطة',
      'لا تستخدمه للمهام التي تتطلب تفكيراً عميقاً'
    ]
  },
  {
    id: 'midjourney-v7',
    slug: 'midjourney-v7',
    name: 'Midjourney v7',
    nameEn: 'Midjourney v7',
    company: 'Midjourney',
    companyEn: 'Midjourney',
    logo: '🟣',
    category: 'image',
    pricing: 'paid',
    pricingDetails: 'مدفوع — يبدأ من $10/شهر',
    website: 'https://midjourney.com',
    description: 'أفضل نموذج لتوليد الصور الفنية — جودة فنية استثنائية وتحكم دقيق بالإضاءة والعدسات والتفاصيل. الأشهر عالمياً في تصميم الصور بالذكاء الاصطناعي.',
    descriptionEn: 'The best model for artistic image generation — exceptional artistic quality with precise control over lighting, lenses, and details. The most famous AI image generator worldwide.',
    strengths: ['جودة فنية استثنائية', 'تحكم دقيق بالإضاءة والعدسات', 'undreds من الأساليب الفنية', 'مجتمع ضخم من المصممين', 'تحديثات مستمرة'],
    weaknesses: ['مدفوع بالكامل', 'يعمل عبر Discord فقط (أو ويب)', 'بطيء في الأوقات المزدحمة', 'لا يفهم العربية جيداً'],
    bestFor: ['الصور الفنية والإبداعية', 'تصميم الملصقات والشعارات', 'الصور الواقعية والسينمائية', 'التصاميم الإعلانية', 'بورتريه الأشخاص'],
    contextWindow: '—',
    languages: ['الإنجليزية فقط'],
    releasedDate: '2025',
    version: '7',
    features: [
      { name: 'Style Tuner', nameAr: 'معادل الأسلوب', description: 'تخصيص أسلوب التوليد بالكامل' },
      { name: 'Permutation Prompts', nameAr: 'برومبتات التبديل', description: 'توليد عدة نسخ ببرومبت واحد' },
      { name: 'Multi-prompt', nameAr: 'برومبت متعدد', description: 'دمج عدة أفكار في برومبت واحد' },
      { name: 'Region Variations', nameAr: 'تنويعات المنطقة', description: 'تعديل جزء محدد من الصورة' },
    ],
    tips: [
      'استخدم "--ar 16:9" للصور الأفقية و"--ar 9:16" للعمودية',
      'أضف "--style raw" لأسلوب أقل إبداعية وأكثر واقعية',
      'استخدم "--chaos 30" للحصول على نتائج متنوعة',
      'ابدأ بـ "/imagine" ثم اكتب وصفك بالإنجليزية فقط'
    ]
  },
  {
    id: 'flux-1-1-pro',
    slug: 'flux-1-1-pro',
    name: 'FLUX 1.1 Pro',
    nameEn: 'FLUX 1.1 Pro',
    company: 'Black Forest Labs',
    companyEn: 'Black Forest Labs',
    logo: '⚫',
    category: 'image',
    pricing: 'freemium',
    pricingDetails: 'مجاني محدود + API مدفوع',
    website: 'https://blackforestlabs.ai',
    description: 'نموذج توليد الصور المفتوح المصدر — جودة عالية جداً ومجاني للاستخدام الأساسي. بديل قوي لـ Midjourney مع مرونة أكبر.',
    descriptionEn: 'Open-source image generation model — very high quality and free for basic use. A powerful alternative to Midjourney with more flexibility.',
    strengths: ['مفتوح المصدر', 'جودة عالية جداً', 'مجاني للاستخدام الأساسي', 'تحكم دقيق بالتفاصيل', 'يدعم ControlNet'],
    weaknesses: ['أقل جمالية من Midjourney أحياناً', 'الواجهة أقل سهولة', 'مجتمع أصغر'],
    bestFor: ['الصور الواقعية جداً', 'الصور التي تحتاج تحكماً دقيقاً', 'المشاريع مفتوحة المصدر', 'البروتيب السريع'],
    contextWindow: '—',
    languages: ['الإنجليزية'],
    releasedDate: '2024',
    version: '1.1',
    features: [
      { name: 'ControlNet', nameAr: 'ControlNet', description: 'تحكم بالأنماط والهياكل في الصورة' },
      { name: 'Open Source', nameAr: 'مفتوح المصدر', description: 'يمكنك تشغيله على جهازك الخاص' },
      { name: 'Inpainting', nameAr: 'الترميم', description: 'تعديل جزء محدد من الصورة' },
    ],
    tips: [
      'استخدم "photorealistic" و"8k" للصور الواقعية',
      'أضف "cinematic lighting" للحصول على إضاءة سينمائية',
      'استخدم Describe لتحويل الصورة إلى برومبت'
    ]
  },
  {
    id: 'sora',
    slug: 'sora',
    name: 'Sora',
    nameEn: 'Sora',
    company: 'OpenAI',
    companyEn: 'OpenAI',
    logo: '🟢',
    category: 'video',
    pricing: 'paid',
    pricingDetails: 'مدفوع — متاح في ChatGPT Plus/Pro',
    website: 'https://sora.com',
    description: 'نموذج توليد الفيديو من OpenAI — يحول النصوص إلى فيديوهات واقعية حتى 20 ثانية. الأكثر تطوراً في فهم حركة الكاميرا والعين البشرية.',
    descriptionEn: 'Video generation model from OpenAI — transforms text into realistic videos up to 20 seconds. Most advanced in understanding camera movement and human eyes.',
    strengths: ['فيديو واقعي جداً', 'فهم ممتاز لحركة الكاميرا', 'itchFaces طبيعية', 'تعمل مع النص العربي (محدوداً)'],
    weaknesses: ['بطيء جداً (5-20 دقيقة لكل فيديو)', 'مدفوع بالكامل', 'مدة قصيرة (حتى 20 ثانية)', 'أخطاء في التفاصيل الدقيقة'],
    bestFor: ['إعلانات الفيديو القصيرة', 'مشاهد سينمائية', '演示 الأفكار', 'محتوى وسائل التواصل'],
    contextWindow: '—',
    languages: ['الإنجليزية', 'العربية (محدوداً)'],
    releasedDate: '2024',
    version: '1.0',
    features: [
      { name: 'Storyboard', nameAr: 'لوحة القصص', description: 'تخطيط المشاهد قبل التوليد' },
      { name: 'Remix', nameAr: 'Remix', description: 'تعديل فيديو موجود بأسلوب جديد' },
      { name: 'Loop', nameAr: 'تكرار', description: 'إنشاء فيديو ي loop باستمرار' },
      { name: 'Blend', nameAr: 'دمج', description: 'دمج فيديوهتين بسلاسة' },
    ],
    tips: [
      'اكتب وصفاً تفصيلياً للمشهد: الإضاءة، الزاوية، الحركة',
      'استخدم "cinematic" و"shot on 35mm" لأسلوب سينمائي',
      'ابدأ بمشاهد بسيطة ثم عدّل بالـ Remix',
      'استخدم Storyboard لتقسيم الفيديو لمشاهد متعددة'
    ]
  },
  {
    id: 'runway-gen-3',
    slug: 'runway-gen-3',
    name: 'Runway Gen-3 Alpha',
    nameEn: 'Runway Gen-3 Alpha',
    company: 'Runway',
    companyEn: 'Runway',
    logo: '🔴',
    category: 'video',
    pricing: 'freemium',
    pricingDetails: 'مجاني محدود (125 رصيد) + مدفوع',
    website: 'https://runwayml.com',
    description: 'من أقوى أدوات توليد الفيديو — يدعم تحكم الكاميرا المتقدم وMotion Brush و editar الفيديو. سهل الاستخدام نسبياً.',
    descriptionEn: 'One of the most powerful video generation tools — supports advanced camera control, Motion Brush, and video editing. Relatively easy to use.',
    strengths: ['واجهة سهلة الاستخدام', 'Motion Brush للتحكم بالحركة', 'تحكم بالكاميرا المتقدم', 'مجاني محدود', '速度 أسرع من Sora'],
    weaknesses: ['جودة أقل من Sora في بعض الحالات', 'المدة محدودة', 'الـ Free plan محدود جداً'],
    bestFor: ['إعلانات الفيديو السريعة', 'محتوى وسائل التواصل', 'تحريك الصور الثابتة', 'تجرية الأفكار بسرعة'],
    contextWindow: '—',
    languages: ['الإنجليزية'],
    releasedDate: '2024',
    version: '3',
    features: [
      { name: 'Motion Brush', nameAr: 'فرشاة الحركة', description: 'تحديد الأجزاء التي تتحرك في الصورة' },
      { name: 'Camera Control', nameAr: 'تحكم بالكاميرا', description: 'تحديد حركة الكاميرا (zoom, pan, tilt)' },
      { name: 'Multi-motion', nameAr: 'حركات متعددة', description: 'إضافة حركات مختلفة لأجزاء مختلفة' },
    ],
    tips: [
      'ابدأ بصورة ثابتة ثم حركها بـ Motion Brush',
      'استخدم Camera Control لシンプル zoom أو pan',
      'ال motion الأفضل = 4 ثوانٍ فقط — لا تطويل',
      'ارفع صورة واضحة للحصول على أفضل نتيجة'
    ]
  },
  {
    id: 'elevenlabs',
    slug: 'elevenlabs',
    name: 'ElevenLabs',
    nameEn: 'ElevenLabs',
    company: 'ElevenLabs',
    companyEn: 'ElevenLabs',
    logo: '🔊',
    category: 'audio',
    pricing: 'freemium',
    pricingDetails: 'مجاني (10,000 حرف/شهر) + مدفوع',
    website: 'https://elevenlabs.io',
    description: 'أفضل نموذج لتحويل النص إلى كلام (TTS) — أصوات طبيعية جداً بلهجات متعددة. يدعم克隆 الصوت والترجمة الصوتية.',
    descriptionEn: 'The best model for text-to-speech — very natural voices with multiple dialects. Supports voice cloning and speech translation.',
    strengths: ['أصوات طبيعية جداً', '克隆 الصوت بدقة عالية', 'تعدد اللهجات العربية', 'ترجمة صوتية مباشرة', 'مجاني محدود'],
    weaknesses: ['الـ Free plan محدود (10K حرف)', 'بطيء في النصوص الطويلة', 'أحياناً ي丢失 المشاعر'],
    bestFor: ['تحويل النصوص لـ podcast', '配音 الفيديوهات', 'الكتب الصوتية', 'الترجمة الصوتية', '克隆 الصوت'],
    contextWindow: '—',
    languages: ['العربية (licted)', 'الإنجليزية', '+20 لغة'],
    releasedDate: '2024',
    version: '2.0',
    features: [
      { name: 'Voice Cloning', nameAr: '克隆 الصوت', description: 'نسخ صوتك أو أي صوت آخر بدقة عالية' },
      { name: 'Speech Translation', nameAr: 'ترجمة صوتية', description: 'تحويل كلام من لغة لأخرى مع الحفاظ على الصوت' },
      { name: 'Multi-speaker', nameAr: 'متعدد المتحدثين', description: 'إنشاء حوار بين عدة أشخاص' },
    ],
    tips: [
      'استخدم "stability" و"similarity" sliders للتحكم بالطبيعي',
      'ارفق samples قصيرة من الصوت الذي تريد不克隆ه',
      'استخدم Voice Library للبحث عن أصوات جاهزة',
      'انشر الكتب الصوتية والأدلة بصوتك克隆'
    ]
  },
  {
    id: 'suno-v4',
    slug: 'suno-v4',
    name: 'Suno v4',
    nameEn: 'Suno v4',
    company: 'Suno',
    companyEn: 'Suno',
    logo: '🎵',
    category: 'audio',
    pricing: 'freemium',
    pricingDetails: 'مجاني (10 أغاني/يوم) + مدفوع',
    website: 'https://suno.com',
    description: 'أقوى نموذج لتوليد الموسيقى بالذكاء الاصطناعي — يحول النصوص إلى أغاني كاملة مع كلمات وتوزيع موسيقي. مجاني بشكل كبير.',
    descriptionEn: 'The most powerful model for AI music generation — transforms text into complete songs with lyrics and musical arrangement. Very generous free tier.',
    strengths: ['أغاني كاملة (كلمات + توزيع)', 'جودة صوتية عالية', 'uno كبير (10 أغاني/يوم)', 'anj多种 أنماط موسيقية', 'يدعم العربية (محدوداً)'],
    weaknesses: ['بطيء في التوليد (1-3 دقائق)', 'العربية محدودة نسبياً', 'لا تملك حقوق ملكية كاملة في الخطة المجانية'],
    bestFor: ['توليد أغاني عشوائية', 'محتوى بودكاست', 'موسيقى الخلفية', 'تجربة أفكار موسيقية', 'إعلانات صوتية'],
    contextWindow: '—',
    languages: ['الإنجليزية', 'العربية (محدوداً)'],
    releasedDate: '2024',
    version: '4',
    features: [
      { name: 'Full Song Generation', nameAr: 'توليد أغنية كاملة', description: 'كلمات + لحن + توزيع في результат واحد' },
      { name: 'Style Mixing', nameAr: 'دمج الأنماط', description: 'دمج عدة أنماط موسيقية في أغنية واحدة' },
      { name: 'Lyrics Generation', nameAr: 'توليد الكلمات', description: 'توليد كلمات الأغاني تلقائياً' },
    ],
    tips: [
      'اكتب وصفاً للنمط الموسيقي: "acoustic guitar, soft vocals, Arabic pop"',
      'استخدم "[Verse]" و"[Chorus]" لتحديد بنية الأغنية',
      'جرب أنماط مختلفة: pop, rock, electronic, arabic, jazz',
      'شاركة مع "[Instrumental]" إذا أردت موسيقى بدون كلام'
    ]
  },
  {
    id: 'cursor',
    slug: 'cursor',
    name: 'Cursor',
    nameEn: 'Cursor',
    company: 'Anysphere',
    companyEn: 'Anysphere',
    logo: '💻',
    category: 'code',
    pricing: 'freemium',
    pricingDetails: 'مجاني محدود + Pro ($20/شهر)',
    website: 'https://cursor.com',
    description: 'محرر أكواد بالذكاء الاصطناعي — مبني على VS Code مع Claude/GPT مدمج. يفهم المشروع كاملاً ويعدّل عدة ملفات دفعة واحدة.',
    descriptionEn: 'AI-powered code editor — built on VS Code with Claude/GPT integrated. Understands the entire project and edits multiple files at once.',
    strengths: ['فهم كامل للمشروع', 'تعديل عدة ملفات دفعة واحدة', 'مبني على VS Code (熟悉)', 'يدعم Claude + GPT', 'Composer للمهام الكبيرة'],
    weaknesses: ['بطيء في المشاريع الكبيرة جداً', 'الـ Free plan محدود', 'أحياناً يغير كود غير مطلوب'],
    bestFor: ['تطوير البرمجيات', 'إعادة هيكلة الكود', 'تصحيح الأخطاء البرمجية', 'إضافة ميزات جديدة', 'فهم مشاريع كودية كبيرة'],
    contextWindow: 'يعتمد على النموذج',
    languages: ['جميع لغات البرمجة'],
    releasedDate: '2024',
    version: '0.45+',
    features: [
      { name: 'Composer', nameAr: 'Composer', description: 'تعديل عدة ملفات في مشروع واحد بمحادثة واحدة' },
      { name: 'Codebase Context', nameAr: 'سياق قاعدة الكود', description: 'يفهم المشروع كاملاً عند كتابة التعليمات' },
      { name: '.cursorrules', nameAr: '.cursorrules', description: 'ملف قواعد مخصص لكل مشروع' },
      { name: 'Multi-file Edit', nameAr: 'تعديل متعدد الملفات', description: 'عدّل أي عدد من الملفات في نفس الوقت' },
    ],
    tips: [
      'أنشئ ملف .cursorrules في جذر المشروع لتعليمات مخصصة',
      'استخدم @codebase ل إشارة لقاعدة الكود بالكامل',
      'استخدم Composer للمهام الكبيرة بدلاً من Chat',
      'راجع كل تغيير قبل القبول — لا تثق أعمى'
    ]
  },
  {
    id: 'claude-code',
    slug: 'claude-code',
    name: 'Claude Code',
    nameEn: 'Claude Code',
    company: 'Anthropic',
    companyEn: 'Anthropic',
    logo: '🟠',
    category: 'code',
    pricing: 'paid',
    pricingDetails: 'مدفوع — يعمل مع Claude API',
    website: 'https://docs.anthropic.com/en/docs/claude-code',
    description: 'أداة سطر أوامر بالذكاء الاصطناعي من Anthropic — تفاعل مباشر مع ملفاتك وGit و终端. الأقوى في فهم المشاريع الكبيرة وإجراء التعديلات المعقدة.',
    descriptionEn: 'AI command-line tool from Anthropic — direct interaction with your files and Git. Most powerful for understanding large projects and making complex changes.',
    strengths: ['تفاعل مباشر مع filesystem', 'فهم Git والتاريخ', 'المشاريع الكبيرة جداً', 'أمان متقدم (تطلب إذن قبل التعديل)', 'يعمل في terminal'],
    weaknesses: ['يحتاج terminal', 'أبطأ من Cursor في المهام البسيطة', 'مدفوع بالكامل'],
    bestFor: ['إدارة مشاريع DevOps', 'تحسين قواعد الكود الكبيرة', 'المهام التي تحتاج سياق واسع', 'Security reviews', 'DevOps automation'],
    contextWindow: '200,000 توكن',
    languages: ['جميع لغات البرمجة'],
    releasedDate: '2025',
    version: '1.0',
    features: [
      { name: 'Git Integration', nameAr: 'تكامل Git', description: 'يفهم commit history ويقترح تحسينات' },
      { name: 'File System Access', nameAr: 'الوصول لنظام الملفات', description: 'يقرأ ويعدّل الملفات مباشرة' },
      { name: 'Permission System', nameAr: 'نظام الأذونات', description: 'يطلب إذنك قبل كل تعديل' },
    ],
    tips: [
      'ابدأ بـ "告诉我 عن هذا المشروع" لفهم الكود',
      'استخدمه لـ code review قبل كل commit',
      'اطلب "اشرح لي كيف يعمل هذا الملف" لفهم быст',
      'استخدمه مع .claude/settings.json لتخصيص سلوكه'
    ]
  },
  {
    id: 'mistral-large',
    slug: 'mistral-large',
    name: 'Mistral Large',
    nameEn: 'Mistral Large',
    company: 'Mistral AI',
    companyEn: 'Mistral AI',
    logo: '🌊',
    category: 'text',
    pricing: 'freemium',
    pricingDetails: 'مجاني محدود + API مدفوع',
    website: 'https://mistral.ai',
    description: 'نموذج أوروبي قوي — مفتوح المصدر جزئياً ویدعم العربية. بديل ممتاز لـ GPT-4 وClaude مع خصوصية أفضل.',
    descriptionEn: 'A strong European model — partially open-source with Arabic support. An excellent alternative to GPT-4 and Claude with better privacy.',
    strengths: ['مفتوح المصدر جزئياً', 'خصوصية أفضل (بيانات أوروبية)', 'عربي + لغات متعددة', 'أداء ممتاز مقارنة بالتكلفة', 'Mistral Large أقوى من أقرانه'],
    weaknesses: ['مجتمع أصغر من OpenAI/Anthropic', 'أقل ميزات تفاعلية', 'less documentation available'],
    bestFor: ['الشركات التي تهتم بالخصوصية', 'ال�رمجيات مفتوحة المصدر', 'الترجمة', 'التحليل السريع'],
    contextWindow: '128,000 توكن',
    languages: ['العربية', 'الإنجليزية', 'الفرنسية', '+20 لغة'],
    releasedDate: '2024',
    version: 'Large 2',
    features: [
      { name: 'Open Weights', nameAr: 'أوزان مفتوحة', description: 'يمكنك تشغيله على خادمك الخاص' },
      { name: 'Function Calling', nameAr: 'استدعاء الدوال', description: 'يمكنه استدعاء API خارجية' },
      { name: 'Code Generation', nameAr: 'توليد الكود', description: 'ممتاز في كتابة وفهم الكود' },
    ],
    tips: [
      'استخدم Le Chat (mistral.ai) للتجربة المجانية',
      'ممتاز للترجمة بين العربية والفرنسية',
      'استخدم API الخاص بهم لتقليل التكلفة مقارنة بـ OpenAI'
    ]
  }
];

export const MODEL_COMPARISONS: ModelComparison[] = [
  {
    id: 'claude-vs-gpt-text',
    slug: 'claude-vs-gpt-writing',
    title: 'Claude vs GPT-4o: أيهما أفضل للكتابة؟',
    titleEn: 'Claude vs GPT-4o: Which is Better for Writing?',
    modelA: 'claude-4-opus',
    modelB: 'gpt-4o',
    category: 'الكتابة والمحتوى',
    description: 'مقارنة شاملة بين Claude 4 Opus و GPT-4o في كتابة المقالات والمحتوى الإبداعي والتقني.',
    verdict: 'Claude 4 Opus هو الأفضل للكتابة الطويلة والتحليل العميق، بينما GPT-4o أفضل للمحتوى التفاعلي القصير.',
    criteria: [
      { name: 'Writing Quality', nameAr: 'جودة الكتابة', scores: { 'claude-4-opus': 9.5, 'gpt-4o': 8.5 }, winner: 'claude-4-opus', explanation: 'Claude ينتج نصوصاً أكثر عمقاً وتماسكاً في المقالات الطويلة' },
      { name: 'Creativity', nameAr: 'الإبداعية', scores: { 'claude-4-opus': 8.5, 'gpt-4o': 9 }, winner: 'gpt-4o', explanation: 'GPT-4o أكثر إبداعية في المحتوى الإبداعي القصير والتمارين الأدبية' },
      { name: 'Arabic Support', nameAr: 'دعم العربية', scores: { 'claude-4-opus': 8, 'gpt-4o': 8.5 }, winner: 'gpt-4o', explanation: 'GPT-4o يدعم العربية بشكل أوسع مع خيارات التخصيص' },
      { name: 'Speed', nameAr: 'السرعة', scores: { 'claude-4-opus': 7, 'gpt-4o': 9 }, winner: 'gpt-4o', explanation: 'GPT-4o أسرع استجابة بشكل ملحوظ' },
      { name: 'Long Content', nameAr: 'المحتوى الطويل', scores: { 'claude-4-opus': 9.5, 'gpt-4o': 7 }, winner: 'claude-4-opus', explanation: 'Claude يحافظ على جودة عالية في النصوص الطويلة جداً' },
      { name: 'Cost', nameAr: 'التكلفة', scores: { 'claude-4-opus': 6, 'gpt-4o': 7.5 }, winner: 'gpt-4o', explanation: 'GPT-4o mini أرخص بكثير للاستخدام اليومي' },
    ]
  },
  {
    id: 'midjourney-vs-flux',
    slug: 'midjourney-vs-flux-images',
    title: 'Midjourney vs FLUX: أيهما أفضل لتوليد الصور؟',
    titleEn: 'Midjourney vs FLUX: Which is Better for Image Generation?',
    modelA: 'midjourney-v7',
    modelB: 'flux-1-1-pro',
    category: 'توليد الصور',
    description: 'مقارنة بين أقوى نموذجين لتوليد الصور — Midjourney v7 للفن والجمال، وFLUX للواقعية والمرونة.',
    verdict: 'Midjourney v7 للصور الفنية والإبداعية، FLUX للصور الواقعية والمشاريع مفتوحة المصدر.',
    criteria: [
      { name: 'Artistic Quality', nameAr: 'الجودة الفنية', scores: { 'midjourney-v7': 9.5, 'flux-1-1-pro': 8 }, winner: 'midjourney-v7', explanation: 'Midjourney ينتج صوراً أكثر جمالية وإبداعية' },
      { name: 'Photorealism', nameAr: 'الواقعية', scores: { 'midjourney-v7': 8, 'flux-1-1-pro': 9 }, winner: 'flux-1-1-pro', explanation: 'FLUX ينتج صوراً أكثر واقعية في بعض الحالات' },
      { name: 'Control', nameAr: 'التحكم', scores: { 'midjourney-v7': 7.5, 'flux-1-1-pro': 9 }, winner: 'flux-1-1-pro', explanation: 'FLUX يدعم ControlNet وتحكم أكثر دقة' },
      { name: 'Ease of Use', nameAr: 'سهولة الاستخدام', scores: { 'midjourney-v7': 8.5, 'flux-1-1-pro': 6 }, winner: 'midjourney-v7', explanation: 'Midjourney أسهل في الاستخدام عبر Discord' },
      { name: 'Cost', nameAr: 'التكلفة', scores: { 'midjourney-v7': 6, 'flux-1-1-pro': 8.5 }, winner: 'flux-1-1-pro', explanation: 'FLUX مجاني جزئياً ومفتوح المصدر' },
      { name: 'Speed', nameAr: 'السرعة', scores: { 'midjourney-v7': 7.5, 'flux-1-1-pro': 8 }, winner: 'flux-1-1-pro', explanation: 'FLUX أسرع في بعض الحالات' },
    ]
  },
  {
    id: 'sora-vs-runway-video',
    slug: 'sora-vs-runway-video',
    title: 'Sora vs Runway: أيهما أفضل لتوليد الفيديو؟',
    titleEn: 'Sora vs Runway: Which is Better for Video Generation?',
    modelA: 'sora',
    modelB: 'runway-gen-3',
    category: 'توليد الفيديو',
    description: 'مقارنة بين Sora و Runway Gen-3 في توليد الفيديو من النصوص والصور.',
    verdict: 'Sora للجودة العالية والمدة الأطول، Runway للسرعة وسهولة الاستخدام.',
    criteria: [
      { name: 'Video Quality', nameAr: 'جودة الفيديو', scores: { 'sora': 9, 'runway-gen-3': 8 }, winner: 'sora', explanation: 'Sora ينتج فيديوهات أكثر واقعية وتفاصيل' },
      { name: 'Camera Control', nameAr: 'تحكم بالكاميرا', scores: { 'sora': 8, 'runway-gen-3': 9 }, winner: 'runway-gen-3', explanation: 'Runway يتحكم بالكاميرا بشكل أكثر دقة' },
      { name: 'Speed', nameAr: 'السرعة', scores: { 'sora': 5, 'runway-gen-3': 8 }, winner: 'runway-gen-3', explanation: 'Runway أسرع بكثير في التوليد' },
      { name: 'Duration', nameAr: 'المدة', scores: { 'sora': 8, 'runway-gen-3': 6 }, winner: 'sora', explanation: 'Sora يدعم فيديوهات أطول (حتى 20 ثانية)' },
      { name: 'Ease of Use', nameAr: 'سهولة الاستخدام', scores: { 'sora': 7, 'runway-gen-3': 8.5 }, winner: 'runway-gen-3', explanation: 'Runway واجهة أسهل وأكثر تفاعلية' },
      { name: 'Cost', nameAr: 'التكلفة', scores: { 'sora': 5, 'runway-gen-3': 7 }, winner: 'runway-gen-3', explanation: 'Runway يوفر خطة مجانية أكبر' },
    ]
  },
  {
    id: 'coding-models-comparison',
    slug: 'best-ai-coding-models',
    title: 'أفضل نماذج البرمجة بالذكاء الاصطناعي 2025',
    titleEn: 'Best AI Coding Models 2025',
    modelA: 'cursor',
    modelB: 'claude-code',
    category: 'البرمجة',
    description: 'مقارنة شاملة بين Claude Code و Cursor — أقوى أداة لبرمجة بالذكاء الاصطناعي.',
    verdict: 'Cursor للمبرمجين الذين يفضلون واجهة مرئية، Claude Code للمحترفين الذين يفضلون Terminal.',
    criteria: [
      { name: 'Code Quality', nameAr: 'جودة الكود', scores: { 'cursor': 8.5, 'claude-code': 9.5 }, winner: 'claude-code', explanation: 'Claude Code ينتج كوداً أكثر نظافة وأماناً' },
      { name: 'Project Understanding', nameAr: 'فهم المشروع', scores: { 'cursor': 8, 'claude-code': 9.5 }, winner: 'claude-code', explanation: 'Claude Code يفهم المشاريع الكبيرة بشكل أعمق' },
      { name: 'Speed', nameAr: 'السرعة', scores: { 'cursor': 9, 'claude-code': 7 }, winner: 'cursor', explanation: 'Cursor أسرع في المهام اليومية البسيطة' },
      { name: 'Ease of Use', nameAr: 'سهولة الاستخدام', scores: { 'cursor': 9, 'claude-code': 6 }, winner: 'cursor', explanation: 'Cursor أسهل بكثير للمبتدئين' },
      { name: 'File System', nameAr: 'نظام الملفات', scores: { 'cursor': 7, 'claude-code': 9.5 }, winner: 'claude-code', explanation: 'Claude Code يتفاعل مع filesystem بشكل أعمق' },
      { name: 'Git Integration', nameAr: 'تكامل Git', scores: { 'cursor': 7, 'claude-code': 9 }, winner: 'claude-code', explanation: 'Claude Code يفهم Git history ويقترح تحسينات' },
    ]
  }
];
